### ISSUE TITLE
Body value is [, ]

### ISSUE THREAD

**Issue by eckmLJE** [jarrodparkes/mbox-to-csv#1]
Hi Jarrod, I'm new at using Github so I hope this is the appropriate way to submit this question. 

I've successfully set up Docker and run the script on my mbox file. The script successfully exports subject, from and date into the csv, however the body value shows just "[, ]" in every row. 

The body format in my emails looks like the below. Is this script capable of exporting this kind of content into the body field?

**Name:** Tonya 

**Email Address:** hello@Hello.com

**Phone:** 555-555-55555

**Apartment Type?:** 3BR

**Move-In Date?:** 11/10/2017

**Rent Maximum?:**

**I'm interested in... :** More information...

**Comment by jarrodparkes** [comment]
@eckmLJE correct place for issues. it should be able to export the body of emails. do you have an example .mbox file that you can send me for testing (or reproducing the error)?

**Comment by eckmLJE** [comment]
Thank you @jarrodparkes! I have created this sample data linked below by sending in some test form submissions. 

[Sample Mbox.zip](https://github.com/jarrodparkes/mbox-to-csv/files/1471393/Sample.Mbox.zip)

I exported these mbox files through Google's get your data tools. I have just tested them and got the same result with the body field showing "[, ]".

**Comment by eckmLJE** [comment]
Here is my clean_mail file as well from one of the exports:

[clean_mail.zip](https://github.com/jarrodparkes/mbox-to-csv/files/1471416/clean_mail.zip)

**Comment by jarrodparkes** [comment]
@eckmLJE it should be fixed now. the issue was that the message extraction didn't consider multipart emails where the plaintext is buried within.

try pulling the most recent changes. here was my test:

```
~/Developer/mbox-to-csv $ ./run.sh 
name of mbox file in current directory (ex. my_file.mbox): hendrixsampledata.mbox
name of sender that you want to filter (ex. Jarrod Parkes): 
email of sender that you want to filter (ex. parkesfjarrod@gmail.com): no-reply@squarespace.info
generated csv file called clean_mail.csv
```
