### ISSUE TITLE
Error with unicodecsv as csv and in csv.writer command

### ISSUE THREAD

**Issue by tinkerjoy** [jarrodparkes/mbox-to-csv#11]
I ran the mbox_parser.py using latest code.  I'm using Python 3.8.3.  The two errors are 1) the import unicodecsv as csv and 2) csv.writer error on the encoding clause

commented out (in my copy) the import unicode csv as csv and added an import csv

For the csv.writer error, here is the text:
File "mbox_parser.py", line 32, in <module>
    writer = csv.writer(open(export_file_name, "wb"), encoding='utf-8')
TypeError: 'encoding' is an invalid keyword argument for this function

**Comment by jarrodparkes** [comment]
@tinkerjoy and you have the `unicodecsv` drop-in replacement installed?

`pip install unicodecsv`

**Comment by jarrodparkes** [comment]
try newly merged approach — we can re-open if you are still having issues
