### ISSUE TITLE
ModuleNotFound

### ISSUE THREAD

**Issue by apexred** [jarrodparkes/mbox-to-csv#13]
Hi,

When trying to execute, I get an error:

(env) FallingOTNMC:mbox-to-csv-master Horza$ ls
README.md		VB.mbox			env			example.mbox		mbox_parser.py		requirements.txt

(env) FallingOTNMC:mbox-to-csv-master Horza$ python3 mbox_parser.py VB.mbox
Traceback (most recent call last):
  File "mbox_parser.py", line 1, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'

I can confirm all site-packages are present and correct:
(env) FallingOTNMC:mbox-to-csv-master Horza$ ls
beautifulsoup4-4.9.1.dist-info		email_reply_parser			pkg_resources				soupsieve-2.0.1.dist-info
bs4					email_reply_parser-0.5.9-py3.8.egg-info	setuptools				unicodecsv
bs4-0.0.1-py3.8.egg-info		pip					setuptools-41.2.0.dist-info		unicodecsv-0.14.1-py3.8.egg-info
easy_install.py				pip-20.1.1.dist-info			soupsieve

Am I missing something?

**Comment by jarrodparkes** [comment]
@apexred I don't think. Once you start the virtual env `(env)` can you run `pip list` and paste the contents here?

**Comment by apexred** [comment]
I can admit to being a python doofus so you've probably forgotten more than I'll ever know :-)

(env) FallingOTNMC:mbox-to-csv-master Horza$ pip list
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Package                                Version
-------------------------------------- --------
altgraph                               0.10.2
bdist-mpkg                             0.5.0
bonjour-py                             0.3
macholib                               1.5.1
matplotlib                             1.3.1
modulegraph                            0.10.4
numpy                                  1.8.0rc1
pip                                    20.1.1
py2app                                 0.7.3
pyobjc-core                            2.5.1
pyobjc-framework-Accounts              2.5.1
pyobjc-framework-AddressBook           2.5.1
pyobjc-framework-AppleScriptKit        2.5.1
pyobjc-framework-AppleScriptObjC       2.5.1
pyobjc-framework-Automator             2.5.1
pyobjc-framework-CFNetwork             2.5.1
pyobjc-framework-Cocoa                 2.5.1
pyobjc-framework-Collaboration         2.5.1
pyobjc-framework-CoreData              2.5.1
pyobjc-framework-CoreLocation          2.5.1
pyobjc-framework-CoreText              2.5.1
pyobjc-framework-DictionaryServices    2.5.1
pyobjc-framework-EventKit              2.5.1
pyobjc-framework-ExceptionHandling     2.5.1
pyobjc-framework-FSEvents              2.5.1
pyobjc-framework-InputMethodKit        2.5.1
pyobjc-framework-InstallerPlugins      2.5.1
pyobjc-framework-InstantMessage        2.5.1
pyobjc-framework-LatentSemanticMapping 2.5.1
pyobjc-framework-LaunchServices        2.5.1
pyobjc-framework-Message               2.5.1
pyobjc-framework-OpenDirectory         2.5.1
pyobjc-framework-PreferencePanes       2.5.1
pyobjc-framework-PubSub                2.5.1
pyobjc-framework-QTKit                 2.5.1
pyobjc-framework-Quartz                2.5.1
pyobjc-framework-ScreenSaver           2.5.1
pyobjc-framework-ScriptingBridge       2.5.1
pyobjc-framework-SearchKit             2.5.1
pyobjc-framework-ServiceManagement     2.5.1
pyobjc-framework-Social                2.5.1
pyobjc-framework-SyncServices          2.5.1
pyobjc-framework-SystemConfiguration   2.5.1
pyobjc-framework-WebKit                2.5.1
pyOpenSSL                              0.13.1
pyparsing                              2.0.1
python-dateutil                        1.5
pytz                                   2013.7
scipy                                  0.13.0b1
setuptools                             44.1.1
six                                    1.4.1
xattr                                  0.6.4

**Comment by jarrodparkes** [comment]
@apexred looks like your problem is you are using Python 2.7

> DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support

this script, and its virtual environment, is all setup for Python 3.8.3+

**Comment by apexred** [comment]
Jarred,

Oops.   I thought I was activating v3 but  I have both v2.7 and v3.8 on the machine.  Problem solved and it works a charm.  My knowledge of mbox files, mailbox and python in general has improved exponentially! Many thanks.

Steve

**Comment by jarrodparkes** [comment]
awesome, no problem!
