### ISSUE TITLE
The created CSV file is empty.

### ISSUE THREAD

**Issue by jooyoungseo** [jarrodparkes/mbox-to-csv#3]
Hello,

I have followed your instruction and obtained a csv file; however, the generated file does not have its content other than its column headers.
I am using Windows 10 for your information.
Any help would be so much appreciated.

**Comment by jarrodparkes** [comment]
Have you been able to get the script to work with the example .mbox file?

Jarrod

--
Jarrod Parkes
Mobile Lead, CommentSold
Co-Founder, The Parkes Twins LLC
Email: parkesfjarrod@gmail.com
Work: 256.886.8276
Mobile: 256.679.2647

**Comment by jooyoungseo** [comment]
I used the "example.mbox" as a input file, and the generated "clean_mail.csv" output file does not contain the content of the mbox. It just has the column headers.

I cloned your repo under my `C:\Users` so that I can have my local repo as C:\Users\mbox-to-csv\
And, I typed the following command inside the mbox-to-csv directory:

```
docker run -it --rm --name mbox-to-csv -v /c/Users/mbox-to-csv:/usr/src/myapp -w /usr/src/myapp python:2 python mbox_parser.py
```

I have tried several times using other mbox files; however, the output csv file is empty.

**Comment by jarrodparkes** [comment]
@jooyoungseo if your mbox file doesn't contain any sensitive information, i don't mind trying it myself to see if there is something i need to tweak

**Comment by jooyoungseo** [comment]
Thank you very much for your kind help.

I would like to point out that I was not even able to complete csv output from your provided example.mbox, either.
As I explained above, the output csv file is empty.

Attached is mbox file that I would like to analyze in a csv format.

I have obtained the mbox file using [mailman downloader](https://github.com/corydolphin/mailman-downloader).
What I am trying to do is to collect the following mailing list serve archive in a csv format.
http://nfbnet.org/pipermail/nfbcs_nfbnet.org/

To do so, firstly I downloaded the archive in an mbox format using mailman downloader that I mentioned. Secondly, I was attempting to convert the obtained mbox files into csv.

[2018-February.mbox.txt](https://github.com/jarrodparkes/mbox-to-csv/files/1886035/2018-
[2018-February.mbox.txt](https://github.com/jarrodparkes/mbox-to-csv/files/1886036/2018-February.mbox.txt)
February.mbox.txt)

But, I got stuck.

[2018-February.mbox.txt](https://github.com/jarrodparkes/mbox-to-csv/files/1886037/2018-February.mbox.txt)
[2018-February.mbox.txt](https://github.com/jarrodparkes/mbox-to-csv/files/1886038/2018-February.mbox.txt)
Any help would be so much appreciated.

**Comment by jarrodparkes** [comment]
@jooyoungseo I just tested the instructions in the README, and I was able to generate CSV output without any issue. When you've tried following the instructions, are you using Docker and the `run.sh` script?

As for your .mbox file, I tried downloading it (note: it is provided as a .txt file), but it seems like it may be an invalid file. The contents of it are not readable like the `example.mbox` file that is bundled with this repo.

**Comment by JKAUSHALYA** [comment]
I think this happens if you provide empty name and empty email address to filter. Is there a way to go without any filtering ?

**Comment by derrickdso** [comment]
Also looking for a method that collects all user names and email addresses from the mbox. ^^

**Comment by kevinmtrowbridge** [comment]
The script is very simple, if you look here is where it applies the filters: https://github.com/jarrodparkes/mbox-to-csv/blob/master/mbox_parser.py#L47

`name_filter in message["from"]` ... I think this is just a python language construct.  If one string is "in" another string.  It might take wildcards and other special strings.

EDIT: I tried using `*` and it worked, it returned all the rows.  So just enter `*` to dump everything into the CSV.

**Comment by jarrodparkes** [comment]
thanks @kevinmtrowbridge closing this
