### ISSUE TITLE
Implement with no inputs, get all emails and usernames

### ISSUE THREAD

**Issue by derrickdso** [jarrodparkes/mbox-to-csv#4]
I'm wondering if there is an implementation method that outputs all usernames and emails, without the need for user input.

**Comment by kevinmtrowbridge** [comment]
The script is very simple, if you look here is where it applies the filters: https://github.com/jarrodparkes/mbox-to-csv/blob/master/mbox_parser.py#L47

`name_filter in message["from"]` ... I think this is just a python language construct.  If one string is "in" another string.  It might take wildcards and other special strings.

EDIT: I tried using `*` and it worked, it returned all the rows.  So just enter `*` to dump everything into the CSV.  I don't have a solution for removing user input though.

**Comment by jarrodparkes** [comment]
thanks @kevinmtrowbridge closing this
