### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\u200c' in position 102: ordinal not in range(128)

### ISSUE THREAD

**Issue by barinvon** [jarrodparkes/mbox-to-csv#8]
Getting:

UnicodeEncodeError: 'ascii' codec can't encode character u'\u200c' in position 102: ordinal not in range(128)

When trying to convert an mbox file

**Comment by jarrodparkes** [comment]
@barinvon do you have a .mbox file that I can use to test/reproduce the issue?

**Comment by jarrodparkes** [comment]
please try the solution incorporated into master from #10

**Comment by jarrodparkes** [comment]
try newly merged approach — we can re-open if you are still having issues
