### ISSUE TITLE
another 'ordinal not in range(128)' bug

### ISSUE THREAD

**Issue by greatnoises** [jarrodparkes/mbox-to-csv#9]
hi there,

I'm sorry if this is redundant -- I'm using this for the first time, so I'm not sure if the fact that the error being spit out doesn't explicitly name one character means that this is a new issue, or if this is just a repeat of the other open issues.  I've not really Python-ed more than casually, and I doubt this makes a difference, but I'm running the .py directly, ie sans docker, because I haven't used docker in 3.5 years and ramping back up well enough and quickly enough at the moment isn't feasible.

Much appreciated if you could advise on a fix! I'm getting this error:

mbox-to-csv jmt $ python mbox_parser.py _a_TTT.mbox 

name of mbox file in current directory (ex. my_file.mbox): _a_TTT.mbox
name of sender that you want to filter (ex. Jarrod Parkes, * for any): *
email of sender that you want to filter (ex. parkesfjarrod@gmail.com, * for any): *

Traceback (most recent call last):
  File "mbox_parser.py", line 52, in <module>
    writer.writerow([message["subject"], message["from"], message["date"], contents])
UnicodeEncodeError: 'ascii' codec can't encode characters in position 5614-5616: ordinal not in range(128)

many thanks!

**Comment by jarrodparkes** [comment]
@greatnoises can you attach an `mbox` example?

**Comment by mbcbus** [comment]
I'm also getting this error
```
File "mbox_parser.py", line 52, in <module>
writer.writerow([message["subject"], message["from"], message["date"], contents])
UnicodeEncodeError: 'ascii' codec can't encode character u'\u22c5' in position 1886: ordinal not in range(128)
```

Is it maybe possible to run an option on this script that _doesn't_ try and encode unicode characters? It appears to be the same issue on most issue requests.

Appears to be the dot character: https://www.fileformat.info/info/unicode/char/22c5/index.htm

**Comment by KyrosDigital** [comment]
Faced the same issue. Looking into a possible temporary fix.

**Comment by jarrodparkes** [comment]
@KyrosDigital do you have a `.mbox` file that I can use to test?

**Comment by ESWVistos** [comment]
Have you been able to come up with a solution?
We're having the same issue (with a different Unicode character).
Thanks!

**Comment by jarrodparkes** [comment]
@ESWVistos I haven't yet. Looking for a `.mbox` file to test these issues with. Do you have an example file I can use?

**Comment by ESWVistos** [comment]
Unfortunately, the .mbox file contains client's data and I cannot share it with you.

**Comment by jarrodparkes** [comment]
@ESWVistos is it possible for you to scrub it first (to remove any personal information)?

**Comment by jarrodparkes** [comment]
^ while doing that could eliminate the character causing the issue — it is a better chance at reproducing the issue (so I can fix it) than otherwise

**Comment by moates** [comment]
for quick possible solution, see #10

**Comment by jarrodparkes** [comment]
please try the solution incorporated from #10

**Comment by jarrodparkes** [comment]
try newly merged approach — we can re-open if you are still having issues
